test_suites:
  - name: sast_scan
    script_path: /root/okta/okta-auth-swift/scripts
    script_name: sast_scan
    sort_order: '1'
    timeout: '200'
    criteria: MERGE
    queue_name: small
    trigger: AUTO
