version: 2.1

orbs:
  general-platform-helpers: okta/general-platform-helpers@1.9
  macos: circleci/macos@2

executors:
  apple-ci-arm-medium:
    macos:
      xcode: 26.2.0
    resource_class: m4pro.medium

jobs:
  setup:
    executor: apple-ci-arm-medium
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  snyk-scan:
    executor: apple-ci-arm-medium
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: run swift package show dependencies
          command: swift package show-dependencies
      - macos/install-rosetta
      - general-platform-helpers/step-run-snyk-monitor:
          scan-all-projects: true
          skip-unresolved: false
          os: macos

workflows:
  security-scan:
    jobs:
      - setup #:
         # filters:
         #   branches:
         #     only:
         #       - master
      - snyk-scan:
          name: execute-snyk
          #filters:
          #  branches:
          #    only:
          #      - master
          context:
            - static-analysis
          requires:
            - setup
